export const projdata = [
	{
	  name: 'weeklys',
	  description: 'an efficient competitive programming planner. (winner of HackExeter 2022)',
	  imageSrc: '/images/weeklys.png',
	  imageAlt: 'weeklys / cp planner',
	  site: 'https://onelineaday.vercel.app',
	  gh: 'https://github.com/ryanchou-dev/weeklys',
	  dv: 'https://devpost.com/software/weeklys',
	},
	{
	  name: '~one line a day~',
	  description: 'a minimalistic diary.',
	  imageSrc: '/images/onelineaday.png',
	  imageAlt: 'one line a day / diary',
	  site: 'https://weeklys.vercel.app',
	  gh: 'https://github.com/ryanchou-dev/onelineaday',
	},
	{
	  name: 'cow pattern generation',
	  description: 'what it says ^^',
	  imageSrc: '/images/cowgen.png',
	  imageAlt: 'cow pattern generation / ml',
	  site: '',
	  gh: 'https://github.com/ryanchou-dev/cow_gen',
	},
	{
	  name: 'stresst',
	  description: 'a stress testing package for python and c++ (tested on ubuntu)',
	  imageSrc: '/images/stresst.png',
	  imageAlt: 'stresst / py + cpp',
	  site: '',
	  gh: 'https://github.com/ryanchou-dev/stresst',
	},
]
