export const projdata = [
  {
    name: "ArtMart",
    description: `Trade your art. Find your community. (2nd @ LancerHacks VI)`,
    colab: "oh yawp",
    imageSrc: "/images/projects/artmart.png",
    imageAlt: "weeklys / cp planner",
    site: "https://artmart.vercel.app",
    gh: "https://github.com/ShubhamPatilsd/artmart",
    dv: "https://devpost.com/software/artmart",
  },
  {
    name: "weeklys",
    description:
      "an efficient competitive programming planner. (winner of HackExeter 2022)",
    imageSrc: "/images/projects/weeklys.png",
    imageAlt: "weeklys / cp planner",
    site: "https://weeklys.vercel.app",
    gh: "https://github.com/ryanchou-dev/weeklys",
    dv: "https://devpost.com/software/weeklys",
  },
  {
    name: "~one line a day~",
    description: "a minimalistic diary.",
    imageSrc: "/images/projects/onelineaday.png",
    imageAlt: "one line a day / diary",
    site: "https://onelineaday.vercel.app",
    gh: "https://github.com/ryanchou-dev/onelineaday",
  },
  {
    name: "So... Why does Dijkstra's Algorithm work?",
    description: "wait actually... don't watch this",
    imageSrc: "/images/projects/some2.png",
    imageAlt: "info video / some2",
    site: "https://www.youtube.com/watch?v=yU6p7bpEKAE",
    gh: "",
  },
  {
    name: "cow pattern generation",
    description: "what it says ^^",
    imageSrc: "/images/projects/cowgen.png",
    imageAlt: "cow pattern generation / ml",
    site: "",
    gh: "https://github.com/ryanchou-dev/cow_gen",
  },
  {
    name: "stresst",
    description:
      "a stress testing package for python and c++ (tested on ubuntu)",
    imageSrc: "/images/projects/stresst.png",
    imageAlt: "stresst / py + cpp",
    site: "",
    gh: "https://github.com/ryanchou-dev/stresst",
  },
];
